export const cities = [
    { value: '1', label: 'تهران' },
    { value: '2', label: 'مشهد' },
    { value: '3', label: 'اصفهان' },
    { value: '4', label: 'شیراز' },
    { value: '5', label: 'تبریز' },
    { value: '6', label: 'اهواز' },
    { value: '7', label: 'کرج' },
    { value: '8', label: 'قم' },
    { value: '9', label: 'کرمانشاه' },
    { value: '10', label: 'رشت' },
    { value: '11', label: 'ارومیه' },
    { value: '12', label: 'زاهدان' },
    { value: '13', label: 'همدان' },
    { value: '14', label: 'یزد' },
    { value: '15', label: 'کرمان' },
    { value: '16', label: 'اردبیل' },
    { value: '17', label: 'بندرعباس' },
    { value: '18', label: 'قزوین' },
    { value: '19', label: 'خرم‌آباد' },
    { value: '20', label: 'گرگان' },
    { value: '21', label: 'ساری' },
]